apiVersion: v1
kind: ConfigMap
metadata:
  name: langwatch-config
data:
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  GROQ_API_KEY: ""
  API_TOKEN_JWT_SECRET: ""
  NEXTAUTH_SECRET: ""
  NEXTAUTH_PROVIDER: "email"
  SENDGRID_API_KEY: ""